blog/urls.py
from django.urls import path
from .views import render_posts,post_detail

app_name = "blog"

urlpatterns = [
   path('', render_posts, name='posts'),
   path('<int:post_id>', post_detail, name="post_detail")
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from proyecto import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

proyecto/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post

def render_posts(request):
    posts = Post.objects.all()
    return render(request,'posts.html', {'posts': posts})

def post_detail(request,post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html',{"post": post})

proyecto/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects =Project.objects.all()
    return render(request, 'home.html', {'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}
<div class="text-center">
    <h2>{{post.title}}</h2>
    <h3 class="my-2 h5 text-secondary">{{post.date|date:'F jS Y'}}</h3>

    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid" />

    <div class="my-4">
        <p>{{post.description|safe}}</p>
    </div>
</div>
{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<h1>POSTS</h1>
{% for post in posts %}

<div class="p-3">
    <div class="card card-body bg-black card-project2">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid"/>
            </div>
            <div class="col-9">
                <h2>{{post.title}}</h2>
                <p>{{post.description|truncatechars:200}}</p>
                <p>{{post.date|date:'M d Y'|upper}}</p>
        
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-danger">Ver más...</a>
            </div>
        </div>
    </div>
</div>
{% endfor %} {% endblock %}

proyecto/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<header class="row bg-black">
    <div class="col-md-4">
    <img src="{% static 'portfolio/profileee.png' %}" class="img-fluid"/>
    </div>

    <div class="col-md-8 my-auto">
        <h1> <strong>ALVA EMILY</strong> </h1>
        <h3> DESARROLLADOR WEB BACKEND</h3>
        <P>Profesional apasionada por la tecnología, 
            con una formación sólida en desarrollo web backend,
             conocimiento en lenguajes de programación, 
             administración de base de datos, consumo y creación
              de Apis, además de metodologías agiles. 
              Experiencia laborando en puestos administrativos, 
              desarrollando habilidades como la organización, 
              análisis, gestión y trabajo en equipo para el logro 
              de objetivos.
        </P>
            <a 
                href="{% static 'portfolio/Certificado.pdf' %}" 
                class="btn btn-danger btn-lg rounded-0 my-3"
                target="_blank">Ver Certificación
            </a>
    </div>

</header>
    
<div class="row my-4 text-center">

    <h2>PROYECTOS</h2>
    <p>❖-------------------------------------------------------------------------------❖</p>

{% for project in projects %}

<div class="col-md-4 p-4">
    <div class="card bg-black card-project2">
        <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top" />
        <div class="card-body">
            <div class="text-light">

            <h2>{{project.title}}</h2> <p>{{project.description}}</p>
            

            {% if project.url %}
            <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>

            {% endif %} 
            </div>
        </div>
    </div>
</div>


{% endfor %}
{% endblock %}

</div>

proyecto/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">
    
    {% include 'partials/navdar.html' %}

    <div class="container p-4">
    {% block content %}
    {% endblock %}
    </div>
    
</body>
</html>

proyecto/templates/partials/navdar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-dark">
    <div class="container">
      <label class="brand">
        <a href="/"><img src="{% static 'ae2.0.png' %}"></a>
      </label>
      <a class="navbar-brand text-white" href="/"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-secondary btn-sm" 
                href="{% static 'portfolio/cve.pdf' %}" target="_blank">Download CV</a>
          </li>
          
        </ul>
      </div>
    </div>
  </nav>